/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("net.kyori.indra")
    id("net.kyori.indra.git")
}

repositories {
    mavenLocal()
    mavenCentral()

    maven("https://papermc.io/repo/repository/maven-public/") {
        content {
            includeGroup("io.papermc.paper")
            includeGroup("net.md-5")
        }
    }
    maven("https://repo.glaremasters.me/repository/towny/") {
        content {
            includeGroup("com.palmergames.bukkit.towny")
        }
    }
    maven("https://repo.lucko.me/") {
        content {
            includeGroup("me.lucko")
        }
    }
    maven("https://repo.minebench.de") {
        content {
            includeGroup("de.themoep.connectorplugin")
        }
    }
    // maven("https://jitpack.io") {
    //     content {
    //         includeGroup("com.github.MilkBowl")
    //     }
    // }
    // maven("https://repo.extendedclip.com/content/repositories/placeholderapi/") {
    //     content {
    //         includeGroup("me.clip")
    //     }
    // }
}

dependencies {
    // Server API
    compileOnly("io.papermc.paper", "paper-api", "1.19.3-R0.1-SNAPSHOT")

    // Plugin libs
    compileOnly("cc.mewcraft", "mewcore", "5.16.1")
    compileOnly("me.lucko", "helper", "5.6.13") { isTransitive = false }
    compileOnly("com.palmergames.bukkit.towny", "towny", "0.99.0.0") { isTransitive = false }
}

indra {
    javaVersions().target(17)
}

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}
